services:
  mongodb:
    image: mongo:${MONGO_VERSION:-8}
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      TLS_ENABLED: ${TLS_ENABLED:-false}
    volumes:
      - ./data:/data/db
      - ./certs:/certs:ro
    command: >
      bash -c '
      if [ "$TLS_ENABLED" = "true" ]; then
        docker-entrypoint.sh mongod --tlsMode requireTLS --tlsCertificateKeyFile /certs/mongodb.pem --tlsCAFile /certs/ca.crt --tlsAllowConnectionsWithoutCertificates --bind_ip_all
      else
        docker-entrypoint.sh mongod --bind_ip_all
      fi
      '
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge